name: Destroy Infrastructure

### if you want to change the cloud provider, change the cd command in the workflow (step Terraform Init, step Terraform Destroy)


on:
  workflow_dispatch: # Manual trigger

jobs:
  destroy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v2
        with:
          terraform_wrapper: false

      - name: Configure gcp Credentials
        uses: gcp-actions/configure-gcp-credentials@v2
        with:
          gcp-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          gcp-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          gcp-region: us-east-1


      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v0.6.0
        with:
          version: 'latest'
          project_id: ${{ secrets.GCP_PROJECT }}
          credentials: ${{ secrets.GCP_SA_KEY }}

    
      - name: Install gke-gcloud-auth-plugin
        run: |
          # Install the Google Cloud SDK if it's not already installed
          curl https://sdk.cloud.google.com | bash
          source $HOME/google-cloud-sdk/path.bash.inc
          # Install the plugin using the appropriate command
          gcloud components update
          gcloud components install gke-gcloud-auth-plugin
  
  
      - name: Set up Google Cloud credentials for Terraform
        run: |
          ECHO '${{ secrets.GCP_SA_KEY }}' | base64 --decode > /tmp/key.json
          echo "GOOGLE_CREDENTIALS=/tmp/key.json" >> $GITHUB_ENV
  
      - name: Initialize Terraform
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
        run: |
          cd terraform-gcp
          terraform init
  
      - name: Apply Terraform
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
        run: |
          cd terraform-gcp
          terraform apply -auto-approve
